[package]
name = "login_verification"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
k256 = "0.13.3"
rand_core = "0.6.4"
